# chunk_rules.yml
# Only formats with working loaders & chunker strategies are included.
# Extend when a new loader/strategy lands.

# === E-mail ===
eml:
  strategy: by_email_block
  min_tokens: 30
  max_tokens: 250
  overlap: 10

# === Word Processing ===
docx:
  strategy: by_paragraph
  min_tokens: 50
  max_tokens: 300
  overlap: 20

rtf: # handled via the docx loader path
  strategy: by_paragraph
  min_tokens: 50
  max_tokens: 300
  overlap: 20

# === PDFs ===
pdf:
  strategy: by_paragraph
  min_tokens: 50
  max_tokens: 300
  overlap: 20

# === PowerPoint ===
pptx:
  strategy: by_slide
  min_tokens: 200
  max_tokens: 800
  overlap: 0

# === Plain text ===
txt:
  strategy: split_on_blank_lines
  min_tokens: 40
  max_tokens: 300
  overlap: 15

# New blocks from File A (alphabetical order)

# group related rows, detect delimiter automatically, include headers
csv:
  strategy: split_on_rows
  min_tokens: 1000
  max_tokens: 1160
  overlap: 20

# preserve semantic structure, include headers
html:
  strategy: split_on_headings
  min_tokens: 600
  max_tokens: 760
  overlap: 20

# preserve object integrity, exclude headers/footers
json:
  strategy: split_on_objects
  min_tokens: 300
  max_tokens: 460
  overlap: 20

# group by time periods, exclude headers/footers
log:
  strategy: split_on_timestamp
  min_tokens: 500
  max_tokens: 660
  overlap: 20

# markdown-aware splitting, include headers
md:
  strategy: split_on_headings
  min_tokens: 500
  max_tokens: 660
  overlap: 20

# preserve function boundaries, exclude headers/footers
py:
  strategy: split_on_functions
  min_tokens: 300
  max_tokens: 460
  overlap: 20

# separate sheets, preserve structure, include headers
xlsx:
  strategy: split_on_sheets
  min_tokens: 1200
  max_tokens: 1360
  overlap: 20

# maintain element hierarchy, include headers
xml:
  strategy: split_on_elements
  min_tokens: 600
  max_tokens: 760
  overlap: 20

default:
  strategy: paragraph
  min_tokens: 50
  max_tokens: 250
  overlap: 20
