email:
  split_strategy: split_on_blank_lines
  min_chunk_size: 500
  notes: ignore quoted replies, exclude headers/footers
docx:
  split_strategy: split_on_headings
  min_chunk_size: 700
  notes: collapse tables row-wise, include headers
pdf:
  split_strategy: split_on_pages
  min_chunk_size: 800
  notes: preserve page boundaries, include headers/footers
txt:
  split_strategy: split_on_blank_lines
  min_chunk_size: 400
  notes: simple text processing, exclude headers/footers
html:
  split_strategy: split_on_headings
  min_chunk_size: 600
  notes: preserve semantic structure, include headers
md:
  split_strategy: split_on_headings
  min_chunk_size: 500
  notes: markdown-aware splitting, include headers
csv:
  split_strategy: split_on_rows
  min_chunk_size: 1000
  notes: group related rows, detect delimiter automatically, include headers
json:
  split_strategy: split_on_objects
  min_chunk_size: 300
  notes: preserve object integrity, exclude headers/footers
xml:
  split_strategy: split_on_elements
  min_chunk_size: 600
  notes: maintain element hierarchy, include headers
pptx:
  split_strategy: by_slide
  token_bounds: [200, 800]
  overlap: 0
  notes: one chunk per slide, include headers
xlsx:
  split_strategy: split_on_sheets
  min_chunk_size: 1200
  notes: separate sheets, preserve structure, include headers
rtf:
  split_strategy: split_on_headings
  min_chunk_size: 600
  notes: similar to docx handling, include headers
log:
  split_strategy: split_on_timestamp
  min_chunk_size: 500
  notes: group by time periods, exclude headers/footers
py:
  split_strategy: split_on_functions
  min_chunk_size: 300
  notes: preserve function boundaries, exclude headers/footers
